---

# - block:
#     - name: Check if port is open
#       ansible.builtin.wait_for:
#         port: "{{ deploy_port }}"
#         state: started
#         timeout: 3
#       ignore_errors: true
#       register: port_check

#     - name: set fact port is open if port_check.msg is exist
#       ansible.builtin.set_fact:
#         is_open: false
#       when: port_check.msg is defined

#     - name: set fact port is open if port_check.msg is not exist
#       ansible.builtin.set_fact:
#         is_open: true
#       when: port_check.msg is not defined

#     - name: Print is_open port
#       ansible.builtin.debug:
#         msg: "is_open: {{ is_open }}"

#     - name: Deployment fail if port is already in use
#       ansible.builtin.fail:
#         msg: "Port {{ deploy_port }} already in use"
#       when:
#         - is_open
#   when:
#     - deploy_port is defined
#     - deploy_port > 0

- name: Create systemd service
  ansible.builtin.include_tasks: task-install.yml
  when: deploy_action == "install"

- name: Delete systemd service
  ansible.builtin.include_tasks: task-uninstallyml
  when: deploy_action == "uninstall"
